import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full text-center h-full my-auto flex flex-col justify-center items-center">
        <p>
          Punctuality is a virtue, We love being punctual. Arrange your schedule
          properly !
        </p>
        <a
          href="/signup"
          className="mx-5 my-2 px-2 py-1 rounded-lg bg-green-500 w-fit"
        >
          Get Started
        </a>
      </main>
    </>
  );
}
